version: "3"
services:

   tutorial_spring_label:
      image: tutorial_spring_image
      build: ./services/spring
      container_name: tutorial_spring_container
      ports:
         - 8080:8080
      volumes: 
         - ./shared/tomcat-logs:/tomcat/logs
         - ./shared/spring-logs:/spring/logs
      depends_on:
         - tutorial_kafka_label

   tutorial_zookeeper_label:
      container_name: tutorial_zookeeper_container
      image: tutorial_zookeeper_image
      build: ./services/zookeeper
      ports:
         - 2181:2181

   tutorial_kafka_label:
      container_name: tutorial_kafka_container
      image: tutorial_kafka_image
      build: ./services/kafka
      ports:
         - 9092:9092
      depends_on:
         - tutorial_zookeeper_label

   tutorial_python_label:
      container_name: tutorial_python_container
      image: tutorial_python_image
      build: ./services/python
      volumes:
         - ./shared/python:/shared
      environment:
         - GK_PWD=${PWD}

   # tutorial_kafka2_label:
   #    image: tutorial_kafka2_image
   #    build: ./services/kafka
   #    container_name: tutorial_kafka2_container
   #    ports:
   #       - 9093:9092
   #    volumes:
   #       - ./shared/kafka:/shared


