networks:
   main_network:
      name: ${PROJECT_NAME}_main_network

services:
   spring_label:
      image: ${PROJECT_NAME}_spring_image
      container_name: ${PROJECT_NAME}_spring_container
      build:
         context: ./services/spring
      ports:
         - ${GLOBAL_API_PORT}:${GLOBAL_SPRING_PORT}
      env_file:
         - services/spring/.env
      restart: always
      volumes: 
         - ./shared/tomcat-logs:/tomcat/logs
         - ./shared/spring-logs:/spring/logs
      networks:
         - main_network
      depends_on:
         - mongo_label

   # # This container is there for testing purposes
   # python_label:
   #    container_name: ${PROJECT_NAME}_python_container
   #    image: ${PROJECT_NAME}_python_image
   #    build: ./services/python
   #    volumes:
   #       - ./shared/python:/shared
   #    environment:
   #       - GK_PWD=${PWD}

   mongo_label:
      container_name: ${PROJECT_NAME}_mongo_container
      image: ${PROJECT_NAME}_mongo_image
      build:
         context: ./services/mongodb
      env_file:
         - services/mongodb/.env
      volumes: 
         - ./shared/mongodb/:/data/db
      restart: always
      networks:
         - main_network
      # ports:
      #    - 27017:${MONGO_PORT}

