version: "3"
services:

   tutorial_spring_label:
      image: tutorial_spring_image
      build: ./services/spring
      container_name: tutorial_spring_container
      ports:
         - 8080:8080
      volumes: 
         - ./shared/tomcat-logs:/tomcat/logs
         - ./shared/spring-logs:/spring/logs

   tutorial_kafka_label:
      image: tutorial_kafka_image
      build: ./services/kafka
      container_name: tutorial_kafka_container
      ports:
         - 9092:9092
      volumes:
         - ./shared/kafka:/shared


