version: "3"
services:
   # TODO: use the environment: element instead of arguments
   datalake_spring_label:
      image: datalake_spring_image
      container_name: datalake_spring_container
      build:
         context: ./services/spring
         args:
         - KAFKA_BOOTSTRAP_SERVER=${KAFKA_BOOTSTRAP_SERVER}
         - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
         - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
         - MONGO_HOST=${MONGO_HOST}
         - MONGO_PORT=${MONGO_PORT}
         - SPRING_PORT=${SPRING_PORT}
      ports:
         - 8080:${SPRING_PORT}
      volumes: 
         - ./shared/tomcat-logs:/tomcat/logs
         - ./shared/spring-logs:/spring/logs
      depends_on:
         - datalake_kafka_label
         - datalake_mongo_label

   datalake_zookeeper_label:
      container_name: datalake_zookeeper_container
      image: datalake_zookeeper_image
      build: ./services/zookeeper
      ports:
         - 2181:2181

   datalake_kafka_label:
      container_name: datalake_kafka_container
      image: datalake_kafka_image
      build: ./services/kafka
      ports:
         - 9092:9092
      depends_on:
         - datalake_zookeeper_label

   # datalake_python_label:
   #    container_name: datalake_python_container
   #    image: datalake_python_image
   #    build: ./services/python
   #    volumes:
   #       - ./shared/python:/shared
   #    environment:
   #       - GK_PWD=${PWD}

   datalake_mongo_label:
      container_name: datalake_mongo_container
      image: datalake_mongo_image
      build:
         context: ./services/mongodb
         args:
         - MONGO_USERNAME=${MONGO_ROOT_USERNAME}
         - MONGO_PASSWORD=${MONGO_ROOT_PASSWORD}
      volumes: 
         - datalake_mongo_volume:/data/db
      #    - ./shared/mongo:/data/db
      # ports:
      #    - 27017:${MONGO_PORT}

volumes:
   datalake_mongo_volume: {}