FROM apache/kafka:3.7.0 
EXPOSE 9092
# EXPOSE 80

# RUN apt update -y
# RUN apt upgrade -y
# RUN apt install -y curl
# RUN apt install -y wget
# RUN apt install -y openjdk-17-jdk
# RUN apt install -y openjdk-17-jre
# RUN apt clean 

# RUN wget 'https://dlcdn.apache.org/kafka/3.7.0/kafka_2.13-3.7.0.tgz'
# RUN tar -xzf kafka_2.13-3.7.0.tgz
# WORKDIR kafka_2.13-3.7.0

# # Start the ZooKeeper service
# RUN nohup bin/zookeeper-server-start.sh config/zookeeper.properties &> /shared/zookeeper-server-start.log &
# # Looks like java is needed

# # Open up a new shell
# # Start the Kafka broker service
# RUN nohup bin/kafka-server-start.sh config/server.properties > /shared/kafka-server-start.log &

# CMD ["tail", "-f", "/dev/null"]