FROM confluentinc/cp-kafka:7.4.4

# Apache stores kafka at /opt/kafka/
# FROM apache/kafka:latest
# FROM apache/kafka:3.7.0 
# FROM wurstmeister/kafka:latest
# FROM bitnami/kafka:latest

# EXPOSE 9092
# EXPOSE 80

# # Start the ZooKeeper service
# RUN nohup bin/zookeeper-server-start.sh config/zookeeper.properties &> /shared/zookeeper-server-start.log &
# # Looks like java is needed

# # Open up a new shell
# # Start the Kafka broker service
# RUN nohup bin/kafka-server-start.sh config/server.properties > /shared/kafka-server-start.log &

# CMD ["tail", "-f", "/dev/null"]